name: tf
env:
  TF_VERSION: 0.12.16
  AWS_REGION: ap-northeast-1
  WORKING_DIR: 'modules/**'

#pull request to master: execute tf plan
#push to master: execute tf apply
on:
  pull_request:
    branches: [ master ]
    paths:
      - ${{ env.WORKING_DIR }}
  push:
    branches: [ master ]
    paths:
      - ${{ env.WORKING_DIR }}
jobs:
  terraform:
    name: plan-apply-aws-prod-engage-etc-ecr
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TEAM_API_TOKEN }}

      - name: Terraform Init ${{ env.WORKING_DIR }}
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform init

